spring.application.name=store
spring.datasource.url=jdbc:postgresql://10.91.52.93:5433/store-spring-boot
spring.datasource.username=postgres
spring.datasource.password=ucing123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

logging.level.org.springframework.security=DEBUG

jwt.secret=store-spring-boot-learning-jwt-key-secret
jwt.expiration=3600000