###
GET http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpa2lzQGV4YW1wbGUuY29tIiwiaWF0IjoxNzgzMTc2ODI3LCJleHAiOjE3ODMxODA0Mjd9.DqiE9v39-4fBazCsMGbxg2vR_V9EymPeind1dzk9mmE

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com",
  "password": "secret123"
}

###
PUT http://localhost:8080/users/d07e1443-496d-4f42-a51d-6998d61ba353
Content-Type: application/json

{
  "name": "Doe John",
  "email": "doe@example.com",
  "password": "secret321"
}
